name: Update flake.lock

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 0"

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: update-flake-lock
  cancel-in-progress: true

jobs:
  update-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@89ab342bd48ff7318caf8d39d6a330c7b1df8f2f # v3

      - name: Update flake.lock
        run: nix flake update

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "flake.lock: update inputs"
          title: "flake.lock: update inputs"
          labels: |
            dependencies
            automated
